<?php
$baseUrl = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/') . '/';
define('BASE_URL', $baseUrl);
const UTILS_PATH = 'app' . DIRECTORY_SEPARATOR . 'utils' . DIRECTORY_SEPARATOR;
const CORE_PATH = 'app' . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR;
const CONTROLLER_PATH = 'app' . DIRECTORY_SEPARATOR . 'controllers' . DIRECTORY_SEPARATOR;
const MODEL_PATH = 'app' . DIRECTORY_SEPARATOR . 'models' . DIRECTORY_SEPARATOR;

const CLASS_PATHS = [
    UTILS_PATH,
    CORE_PATH,
    CONTROLLER_PATH,
    MODEL_PATH,
];

const VIEWS = 'app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR;
const CLIENT_COMMON_VIEWS = VIEWS . 'client' . DIRECTORY_SEPARATOR . 'common' . DIRECTORY_SEPARATOR;
const ADMIN_COMMON_VIEWS = VIEWS . 'admin' . DIRECTORY_SEPARATOR . 'common' . DIRECTORY_SEPARATOR;
const PUBLIC_IMAGES = BASE_URL . 'public' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR;
const ADMIN_LTE = BASE_URL . 'app' . DIRECTORY_SEPARATOR . 'libs' . DIRECTORY_SEPARATOR . 'adminlte' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_DIST = ADMIN_LTE . 'dist' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_DIST_JS = ADMIN_LTE_DIST . 'js' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_DIST_CSS = ADMIN_LTE_DIST . 'css' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_PLUGINS = ADMIN_LTE . 'plugins' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_PLUGINS_JS = ADMIN_LTE_PLUGINS . 'js' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_PLUGINS_CSS = ADMIN_LTE_PLUGINS . 'css' . DIRECTORY_SEPARATOR;
